-- MySQL Script generated by MySQL Workbench
-- Tue Mar 26 12:51:15 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`management_companies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`management_companies` (
  `management_id` INT NOT NULL,
  `management_phone` INT(10) NOT NULL,
  `management_email` VARCHAR(45) NOT NULL,
  `management_name` VARCHAR(45) NOT NULL,
  `management_address` VARCHAR(95) NOT NULL,
  `management_rating` INT NULL,
  PRIMARY KEY (`management_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`property_amenities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`property_amenities` (
  `amentites_id` INT NOT NULL,
  `parking` INT(1) NOT NULL,
  `gated` INT(1) NOT NULL,
  `furnished` INT(1) NOT NULL,
  `laundry` INT(1) NOT NULL,
  `wifi_cable` INT(1) NOT NULL,
  `gym` INT(1) NOT NULL,
  PRIMARY KEY (`amentites_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`property_space_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`property_space_types` (
  `space_type_id` INT NOT NULL,
  `bedrooms` INT NOT NULL,
  `bathrooms` INT NOT NULL,
  PRIMARY KEY (`space_type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`property_listings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`property_listings` (
  `listing_id` INT NOT NULL,
  `property_name` VARCHAR(45) NOT NULL,
  `property_management_id` INT NOT NULL,
  `property_price` VARCHAR(45) NOT NULL,
  `property_space_type_id` INT NOT NULL,
  `property_address` VARCHAR(95) NOT NULL,
  `property_rating` INT(1) NULL,
  `property_lease_duration` INT NOT NULL,
  `property_amenities_id` INT NOT NULL,
  PRIMARY KEY (`listing_id`),
  INDEX `fk_property_listings_management_companies_idx` (`property_management_id` ASC),
  INDEX `fk_property_listings_property_space_types1_idx` (`property_space_type_id` ASC),
  INDEX `fk_property_listings_property_amenities1_idx` (`property_amenities_id` ASC),
  CONSTRAINT `fk_property_listings_management_companies0`
    FOREIGN KEY (`property_management_id`)
    REFERENCES `mydb`.`management_companies` (`management_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_property_listings_property_space_types10`
    FOREIGN KEY (`property_space_type_id`)
    REFERENCES `mydb`.`property_space_types` (`space_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_property_listings_property_amenities10`
    FOREIGN KEY (`property_amenities_id`)
    REFERENCES `mydb`.`property_amenities` (`amentites_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
